disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - todo

opt_in_rules:
  - empty_count

included:
  - sdk/ios/GoMailer/Sources

excluded:
  - sdk/ios/GoMailer/Build

reporter: "xcode"
