name: gomailer_flutter_example
description: A Flutter example application for GoMailer Push SDK
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  # Use the published package to validate the live distribution instead of the local path.
  # For local development against source, you can replace this with:
  #   go_mailer_push_sdk:
  #     path: ../../sdk/flutter
  go_mailer_push_sdk: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
