name: go_mailer_push_sdk
description: Go Mailer SDK for Flutter - Cross-platform customer engagement messaging and push notifications
version: 1.3.1
homepage: https://github.com/go-mailer/go-mailer-flutter
repository: https://github.com/go-mailer/go-mailer-flutter
issue_tracker: https://github.com/go-mailer/go-mailer-flutter/issues
documentation: https://docs.go-mailer.com/flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  crypto: ^3.0.3
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  plugin_platform_interface: ^2.1.7
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.9

flutter:
  plugin:
    platforms:
      android:
        package: com.gomailer.go_mailer
        pluginClass: GoMailerPlugin
      ios:
        pluginClass: GoMailerPlugin
      web:
        pluginClass: GoMailerWeb
        fileName: go_mailer_web.dart